import {
  House,
  User02Icon,
  Users,
  Database,
  Activity,
  Megaphone,
  Calendar,
  Settings,
  Search,
  BarChart,
  AppleIntelligenceIcon,
  Lightning,
  Mail01Icon,
} from "@hugeicons/core-free-icons"

export const sidebarMenus = [
  {
    title: "Dashboard",
    icon: House,
    path: "/dashboard",
    heading: "Dashboard",
    description: "Overview of activity and key metrics across your workspace.",
  },
  {
    title: "Analytics",
    icon: BarChart,
    path: "/analytics",
    heading: "Analytics",
    description: "Review performance, trends, and reports for your product.",
  },
  {
    title: "Players",
    icon: User02Icon,
    path: "/players",
    heading: "Players",
    description: "Monitor churn, VIP tier, risk, wallet activity, and deposits.",
  },
  {
    title: "Segments",
    icon: Database,
    path: "/segments",
    heading: "Segments",
    description: "Define and maintain audience segments for targeting.",
  },
  {
    title: "Events",
    icon: Activity,
    path: "/events",
    heading: "Events",
    description: "Track, inspect, and analyze product and user events.",
  },
  {
    title: "Campaigns",
    icon: Megaphone,
    path: "/campaigns",
    heading: "Campaigns",
    description: "Create, launch, and monitor marketing campaigns.",
  },
  {
    title: "Templates",
    icon: Mail01Icon,
    path: "/templates",
    heading: "Email templates",
    description: "Manage reusable HTML layouts for email campaigns and automations.",
  },
  {
    title: "Journeys",
    icon: Calendar,
    path: "/journeys",
    heading: "Journeys",
    description: "Design multi-step experiences for your users.",
  },
  {
    title: "Triggers",
    icon: Lightning,
    path: "/triggers",
    heading: "Triggers",
    description: "Configure automation triggers and notifications.",
  },
  {
    title: "API",
    icon: AppleIntelligenceIcon,
    path: "/api",
    heading: "API",
    description: "Manage the API for your account and workspace.",
  },
  {
    title: "Teams",
    icon: Users,
    path: "/users",
    heading: "Users",
    description: "Manage user accounts, roles, and access.",
  },
  {
    title: "Settings",
    icon: Settings,
    path: "/settings",
    heading: "Settings",
    description: "Manage the settings for your account and workspace.",
  },
] as const
